theme: jekyll-theme-minimal
title: Francesco Paolo Conteduca
description: <img src="https://drive.google.com/file/d/1pnfiyL2aRDD6EFzCQy8qPVBrMNhs5PgI/view?usp=sharing" style="width:100px;height:100px;"><br>Personal Webpage. The views expressed here do not necessarily reflect those of the Bank of Italy.
github: is\_project\_page:false
markdown: kramdown
kramdown:
   auto_ids: true
