theme: jekyll-theme-minimal
title: Francesco Paolo Conteduca
description: Personal Webpage. The views expressed here do not necessarily reflect those of the Bank of Italy.<br><center><img src="https://github.com/fpaoloconteduca/fpaoloconteduca.github.io/raw/main/circle-cropped.png" style="width:150px;height:150px;"></center>
github: is\_project\_page:false
markdown: kramdown
kramdown:
   auto_ids: true
